[package]
name = "rocket-playground"
version = "0.1.0"
authors = ["Magnus Kulke <mkulke@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
